ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3)

      DOUBLE PRECISION MDL_MC,MDL_MB,MDL_MM,MDL_MT,MDL_ME,MDL_MH
     $ ,MDL_MZ,MDL_MW,MDL_MTA

      COMMON/MASSES/ MDL_MC,MDL_MB,MDL_MM,MDL_MT,MDL_ME,MDL_MH,MDL_MZ
     $ ,MDL_MW,MDL_MTA


      DOUBLE PRECISION MDL_WT,MDL_WH,MDL_WTAU,MDL_WZ,MDL_WW

      COMMON/WIDTHS/ MDL_WT,MDL_WH,MDL_WTAU,MDL_WZ,MDL_WW


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_50, GC_51, GC_58, GC_59,
     $  GC_84, GC_93

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_50, GC_51, GC_58, GC_59,
     $  GC_84, GC_93

