ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MB,MDL_MTA,MDL_MH,MDL_MZ,MDL_MW

      COMMON/MASSES/ MDL_MT,MDL_MB,MDL_MTA,MDL_MH,MDL_MZ,MDL_MW


      DOUBLE PRECISION MDL_WH,MDL_WZ,MDL_WT,MDL_WW

      COMMON/WIDTHS/ MDL_WH,MDL_WZ,MDL_WT,MDL_WW


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_50, GC_58, GC_59

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_50, GC_58, GC_59

